// apps/angular-app/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

import { common, common2, WelcomeMessage } from '@mono-repo/common';
// import { WelcomeMessage } from '@interfaces/WelcomeMessage';

@Component({
  selector: 'angular-app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
})
export class HomeComponent implements OnInit {

  public message: WelcomeMessage = {
    id: 'Angular',
    message: `Hello`
  };

  constructor() {}

  ngOnInit(): void {
    console.log('common', common());
    console.log('common2', common2());
  }
}

<p>{{ message.id }} - {{ message.message }}</p>

// apps/react-app/src/app/home/home.tsx
import { useEffect, useState } from "react";

import { common, common2, WelcomeMessage } from "@mono-repo/common";

/* eslint-disable-next-line */
export interface HomeProps {}

export function Home(props: HomeProps) {
  const [message, setMessage] = useState<WelcomeMessage>({
    id: 'React',
    message: 'Hallo'
  });

  useEffect(() => {
    console.log('common', common());
    console.log('common2', common2());
  }, []);

  return (
    <p>{message.id} - {message.message}</p>
  );
}

export default Home;
